#!/bin/bash
for file in build/libs/*.jar; do 
	if [[ ${file} != *"-modcore.jar"* ]]; then
		curl -i -H 'Expect: application/json' -F file=@"$file" -F "payload_json={ \"wait\": true, \"content\": \"Build artefact from $TRAVIS_JOB_NAME\nFor logs see $TRAVIS_JOB_WEB_URL\", \"username\": \"Travis CI\" }" $WEBHOOK_URL
	fi
done